import { toHex } from '@metamask/controller-utils';

import type { SwapsToken } from './swapsInterfaces';

//* Chain IDs and names

export const ETH_CHAIN_ID = toHex('1');
export const BSC_CHAIN_ID = toHex('56');
export const POLYGON_CHAIN_ID = toHex('137');
export const AVALANCHE_CHAIN_ID = toHex('43114');
export const ARBITRUM_CHAIN_ID = toHex('42161');
export const OPTIMISM_CHAIN_ID = toHex('10');
export const ZKSYNC_ERA_CHAIN_ID = toHex('324');
export const LINEA_CHAIN_ID = toHex('59144');
export const SWAPS_TESTNET_CHAIN_ID = toHex('1337');
export const BASE_CHAIN_ID = toHex('8453');

export const CHAIN_ID_TO_NAME_MAP: { [key: string]: string } = {
  [ETH_CHAIN_ID]: 'ethereum',
  [BSC_CHAIN_ID]: 'bsc',
  [POLYGON_CHAIN_ID]: 'polygon',
  [AVALANCHE_CHAIN_ID]: 'avalanche',
  [ARBITRUM_CHAIN_ID]: 'arbitrum',
  [OPTIMISM_CHAIN_ID]: 'optimism',
  [ZKSYNC_ERA_CHAIN_ID]: 'zksync',
  [LINEA_CHAIN_ID]: 'linea',
  [SWAPS_TESTNET_CHAIN_ID]: 'ethereum',
  [BASE_CHAIN_ID]: 'base',
};

//* APIs base urls

export const API_BASE_URL = 'https://swap.api.cx.metamask.io';
export const DEV_BASE_URL = 'https://swap.dev-api.cx.metamask.io';
export const GAS_API_BASE_URL = 'https://gas.api.cx.metamask.io';

//* Contract addresses

export const ETH_SWAPS_CONTRACT_ADDRESS =
  '0x881d40237659c251811cec9c364ef91dc08d300c';
export const BSC_SWAPS_CONTRACT_ADDRESS =
  '0x1a1ec25dc08e98e5e93f1104b5e5cdd298707d31';
export const POLYGON_SWAPS_CONTRACT_ADDRESS =
  '0x1a1ec25dc08e98e5e93f1104b5e5cdd298707d31';
export const AVALANCHE_SWAPS_CONTRACT_ADDRESS =
  '0x1a1ec25dc08e98e5e93f1104b5e5cdd298707d31';
export const ARBITRUM_SWAPS_CONTRACT_ADDRESS =
  '0x9dda6ef3d919c9bc8885d5560999a3640431e8e6';
export const OPTIMISM_SWAPS_CONTRACT_ADDRESS =
  '0x9dda6ef3d919c9bc8885d5560999a3640431e8e6';
export const ZKSYNC_ERA_SWAPS_CONTRACT_ADDRESS =
  '0xf504c1fe13d14df615e66dcd0abf39e60c697f34';
export const LINEA_SWAPS_CONTRACT_ADDRESS =
  '0x9dda6ef3d919c9bc8885d5560999a3640431e8e6';
export const BASE_SWAPS_CONTRACT_ADDRESS =
  '0x9dda6ef3d919c9bc8885d5560999a3640431e8e6';

export const WETH_CONTRACT_ADDRESS =
  '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2';
export const WBNB_CONTRACT_ADDRESS =
  '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c';
export const WMATIC_CONTRACT_ADDRESS =
  '0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270';
export const WAVAX_CONTRACT_ADDRESS =
  '0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7';
export const WETH_ARBITRUM_CONTRACT_ADDRESS =
  '0x82af49447d8a07e3bd95bd0d56f35241523fbab1';
export const WETH_OPTIMISM_CONTRACT_ADDRESS =
  '0x4200000000000000000000000000000000000006';
export const WETH_ZKSYNC_ERA_CONTRACT_ADDRESS =
  '0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91';
export const WETH_LINEA_CONTRACT_ADDRESS =
  '0xe5D7C2a44FfDDf6b295A15c148167daaAf5Cf34f';
export const WETH_BASE_CONTRACT_ADDRESS =
  '0x4200000000000000000000000000000000000006';

export const SWAPS_WRAPPED_TOKENS_ADDRESSES: { [key: string]: string } = {
  [ETH_CHAIN_ID]: WETH_CONTRACT_ADDRESS,
  [SWAPS_TESTNET_CHAIN_ID]: WETH_CONTRACT_ADDRESS,
  [BSC_CHAIN_ID]: WBNB_CONTRACT_ADDRESS,
  [POLYGON_CHAIN_ID]: WMATIC_CONTRACT_ADDRESS,
  [AVALANCHE_CHAIN_ID]: WAVAX_CONTRACT_ADDRESS,
  [ARBITRUM_CHAIN_ID]: WETH_ARBITRUM_CONTRACT_ADDRESS,
  [OPTIMISM_CHAIN_ID]: WETH_OPTIMISM_CONTRACT_ADDRESS,
  [ZKSYNC_ERA_CHAIN_ID]: WETH_ZKSYNC_ERA_CONTRACT_ADDRESS,
  [LINEA_CHAIN_ID]: WETH_LINEA_CONTRACT_ADDRESS,
  [BASE_CHAIN_ID]: WETH_BASE_CONTRACT_ADDRESS,
};

export const SWAPS_CONTRACT_ADDRESSES: { [key: string]: string } = {
  [ETH_CHAIN_ID]: ETH_SWAPS_CONTRACT_ADDRESS,
  [SWAPS_TESTNET_CHAIN_ID]: ETH_SWAPS_CONTRACT_ADDRESS,
  [BSC_CHAIN_ID]: BSC_SWAPS_CONTRACT_ADDRESS,
  [POLYGON_CHAIN_ID]: POLYGON_SWAPS_CONTRACT_ADDRESS,
  [AVALANCHE_CHAIN_ID]: AVALANCHE_SWAPS_CONTRACT_ADDRESS,
  [ARBITRUM_CHAIN_ID]: ARBITRUM_SWAPS_CONTRACT_ADDRESS,
  [OPTIMISM_CHAIN_ID]: OPTIMISM_SWAPS_CONTRACT_ADDRESS,
  [ZKSYNC_ERA_CHAIN_ID]: ZKSYNC_ERA_SWAPS_CONTRACT_ADDRESS,
  [LINEA_CHAIN_ID]: LINEA_SWAPS_CONTRACT_ADDRESS,
  [BASE_CHAIN_ID]: BASE_SWAPS_CONTRACT_ADDRESS,
};

export const ALLOWED_CONTRACT_ADDRESSES: { [key: string]: string[] } = {
  [ETH_CHAIN_ID]: [
    SWAPS_CONTRACT_ADDRESSES[ETH_CHAIN_ID],
    SWAPS_WRAPPED_TOKENS_ADDRESSES[ETH_CHAIN_ID],
  ],
  [SWAPS_TESTNET_CHAIN_ID]: [
    SWAPS_CONTRACT_ADDRESSES[SWAPS_TESTNET_CHAIN_ID],
    SWAPS_WRAPPED_TOKENS_ADDRESSES[SWAPS_TESTNET_CHAIN_ID],
  ],
  [BSC_CHAIN_ID]: [
    SWAPS_CONTRACT_ADDRESSES[BSC_CHAIN_ID],
    SWAPS_WRAPPED_TOKENS_ADDRESSES[BSC_CHAIN_ID],
  ],
  [POLYGON_CHAIN_ID]: [
    SWAPS_CONTRACT_ADDRESSES[POLYGON_CHAIN_ID],
    SWAPS_WRAPPED_TOKENS_ADDRESSES[POLYGON_CHAIN_ID],
  ],
  [AVALANCHE_CHAIN_ID]: [
    SWAPS_CONTRACT_ADDRESSES[AVALANCHE_CHAIN_ID],
    SWAPS_WRAPPED_TOKENS_ADDRESSES[AVALANCHE_CHAIN_ID],
  ],
  [ARBITRUM_CHAIN_ID]: [
    SWAPS_CONTRACT_ADDRESSES[ARBITRUM_CHAIN_ID],
    SWAPS_WRAPPED_TOKENS_ADDRESSES[ARBITRUM_CHAIN_ID],
  ],
  [OPTIMISM_CHAIN_ID]: [
    SWAPS_CONTRACT_ADDRESSES[OPTIMISM_CHAIN_ID],
    SWAPS_WRAPPED_TOKENS_ADDRESSES[OPTIMISM_CHAIN_ID],
  ],
  [ZKSYNC_ERA_CHAIN_ID]: [
    SWAPS_CONTRACT_ADDRESSES[ZKSYNC_ERA_CHAIN_ID],
    SWAPS_WRAPPED_TOKENS_ADDRESSES[ZKSYNC_ERA_CHAIN_ID],
  ],
  [LINEA_CHAIN_ID]: [
    SWAPS_CONTRACT_ADDRESSES[LINEA_CHAIN_ID],
    SWAPS_WRAPPED_TOKENS_ADDRESSES[LINEA_CHAIN_ID],
  ],
  [BASE_CHAIN_ID]: [
    SWAPS_CONTRACT_ADDRESSES[BASE_CHAIN_ID],
    SWAPS_WRAPPED_TOKENS_ADDRESSES[BASE_CHAIN_ID],
  ],
};

//* Tokens

export const NATIVE_SWAPS_TOKEN_ADDRESS =
  '0x0000000000000000000000000000000000000000';

export const ETH_SWAPS_TOKEN_OBJECT: SwapsToken = {
  symbol: 'ETH',
  name: 'Ether',
  address: NATIVE_SWAPS_TOKEN_ADDRESS,
  decimals: 18,
};

export const BSC_SWAPS_TOKEN_OBJECT: SwapsToken = {
  symbol: 'BNB',
  name: 'Binance Coin',
  address: NATIVE_SWAPS_TOKEN_ADDRESS,
  decimals: 18,
};

export const POLYGON_SWAPS_TOKEN_OBJECT: SwapsToken = {
  symbol: 'POL',
  name: 'Polygon',
  address: NATIVE_SWAPS_TOKEN_ADDRESS,
  decimals: 18,
};

export const AVALANCHE_SWAPS_TOKEN_OBJECT: SwapsToken = {
  symbol: 'AVAX',
  name: 'Avalanche',
  address: NATIVE_SWAPS_TOKEN_ADDRESS,
  decimals: 18,
};

export const ARBITRUM_SWAPS_TOKEN_OBJECT: SwapsToken = {
  ...ETH_SWAPS_TOKEN_OBJECT,
};

export const OPTIMISM_SWAPS_TOKEN_OBJECT: SwapsToken = {
  ...ETH_SWAPS_TOKEN_OBJECT,
};

export const ZKSYNC_ERA_SWAPS_TOKEN_OBJECT: SwapsToken = {
  ...ETH_SWAPS_TOKEN_OBJECT,
};

export const LINEA_SWAPS_TOKEN_OBJECT: SwapsToken = {
  ...ETH_SWAPS_TOKEN_OBJECT,
};

export const BASE_SWAPS_TOKEN_OBJECT: SwapsToken = {
  ...ETH_SWAPS_TOKEN_OBJECT,
};

export const SWAPS_NATIVE_TOKEN_OBJECTS: { [key: string]: SwapsToken } = {
  [ETH_CHAIN_ID]: ETH_SWAPS_TOKEN_OBJECT,
  [SWAPS_TESTNET_CHAIN_ID]: ETH_SWAPS_TOKEN_OBJECT,
  [BSC_CHAIN_ID]: BSC_SWAPS_TOKEN_OBJECT,
  [POLYGON_CHAIN_ID]: POLYGON_SWAPS_TOKEN_OBJECT,
  [AVALANCHE_CHAIN_ID]: AVALANCHE_SWAPS_TOKEN_OBJECT,
  [ARBITRUM_CHAIN_ID]: ARBITRUM_SWAPS_TOKEN_OBJECT,
  [OPTIMISM_CHAIN_ID]: OPTIMISM_SWAPS_TOKEN_OBJECT,
  [ZKSYNC_ERA_CHAIN_ID]: ZKSYNC_ERA_SWAPS_TOKEN_OBJECT,
  [LINEA_CHAIN_ID]: LINEA_SWAPS_TOKEN_OBJECT,
  [BASE_CHAIN_ID]: BASE_SWAPS_TOKEN_OBJECT,
};

//* Other

export const TOKEN_TRANSFER_LOG_TOPIC_HASH =
  '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef';

export const DEFAULT_ERC20_APPROVE_GAS = '0x1d4c0';

// The MAX_GAS_LIMIT is a number that is higher than the maximum gas costs we have observed on any aggregator
export const MAX_GAS_LIMIT = 2500000;
